apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sourcery.fullname" . }}-frontend
  labels:
    {{- include "sourcery.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sourcery.fullname" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sourcery.fullname" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "sourcery.frontend.image" . }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcery.fullname" . }}-frontend
  labels:
    {{- include "sourcery.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sourcery.fullname" . }}
    app.kubernetes.io/component: frontend
